### ISSUE TITLE
კითხვა ანგულარის ვერსიასთან დაკავშირებით

### ISSUE THREAD

**Issue by mariamtsartsidze** [mariamtsartsidze/3Line_webApp#1]
გამარჯობა.
ანგულარის კონკრეტულად რომელი ვერსია უნდა ვისწავლოთ ჩვენი ვებ აპლიკაციისთვის?

**Comment by davidgabrichidze** [comment]
@mariamtsartsidze ბოლო ვერსია [https://angular.io/](https://angular.io/)

ამ ვერსიებს ვიყენებთ ამ მომენტისთვის:
![image](https://user-images.githubusercontent.com/12189125/43683025-c4dc0024-9894-11e8-8907-f9a77a6aa836.png)

**Comment by mariamtsartsidze** [comment]
@davidgabrichidze გმადლობ
