### ISSUE TITLE
Lazy loading - რაღაც გაურკვეველი ერორი

### ISSUE THREAD

**Issue by mariamtsartsidze** [mariamtsartsidze/3Line_webApp#2]
გამარჯობა,
Lazy Loading გავიარე ანგულარში ახლახან და მეგონა, რომ ყველაფერი კარგად იყო, მაგრამ აღმოჩნდა, რომ თუ პროცესს გავაჩერებ ტერმინალიდან და თავიდან დავაკომპილირებ, აი ასეთ ერორს აგდებს:

> ERROR in Could not resolve module ../events/user/user.module relative to/C/Users/Tsartso/Documents/ng-fundamentals/src/app/app.module.ts

მაგრამ თუ რამე შევცვალე კოდში (თუნდაც დავაკომენტარე კოდის რაღაც ნაწილი და განვაკომენტარე), მაშინ ხელახლა დაკოპილირებისას კომპილირდება უპრობლემოდ. 
სხვებსაც ჰქონიათ ასეთი პრობლემები, მაგალითად აი აქ ბევრი წერს: 
[https://github.com/angular/angular-cli/issues/8641](url)
ზოგს ეს პრობლემა absolute path-ის relative path-ით შეცვლამ მოუგვარა. მე თავიდანვე relative path-ს ვიყენებდი, absolute-იც ვცადე, არანაირი შედეგი. თქვენ თუ გქონიათ მსგავსი პრობლემა და ხომ ვერ მირჩევდით რა ვუყო?

**Comment by mariamtsartsidze** [comment]
გავასწორე, მაგრამ იმას მაინც ვერ ვხვდები, ხანდახან რატომ კომპილირდებოდა. ძალიან უცნაურია.

**Comment by davidgabrichidze** [comment]
მარიამ, ატვირთე კოდი,  გაგვიადვილდება დიაგნოსტიკა ორივეს.

მსგავსი ერორი არ მქონია

**Comment by mariamtsartsidze** [comment]
მას მერე ბევრი რამ შევცვალე სავარჯიშო პროექტში და აზრი აღარ აქვს, მადლობა.

**Comment by davidgabrichidze** [comment]
და  ეს სავარჯიშო კოდი ატვირთე. აქ ხომ მხოლოდ საბოლოო  ვერსიის ასატვირთად არ ვართ :)

**Comment by mariamtsartsidze** [comment]
ანუ სულ სხვა რაღაცაა, ჩვენს დავალებასთან არაა კავშირში და ჩემიც არაა, მაგიტომ არ ვტვირთავ, ერთ კურსს ჩავუჯექი pluralsight-ზე, ისინი აწყობენ საცდელ აპლიკაციას და ასე ასწავლიან და იქ მქონდა ეს ერორი.

**Comment by davidgabrichidze** [comment]
ok.  ჩვენსაზე რას შვები? ახლოვდება 20  აგვისტო

**Comment by mariamtsartsidze** [comment]
მალე უნდა დავიწყო წესით და დანარჩენს კეთების პროცესში ვისწავლი, ოღონდ ჯერ ანგულარის ეს კურსი უნდა დავამთავრო და tour of heroes დავწერო. გამომდინარე იქიდან, რომ აქამდე შეხება არ მქონია ჯავასკრიპტთანაც კი, ნიადაგის შემზადებამ წაიღო ეს დრო ძირითადად.
