### ISSUE TITLE
როგორ შევქმნა ვებ სერვერი?

### ISSUE THREAD

**Issue by mariamtsartsidze** [mariamtsartsidze/3Line_webApp#3]
გამარჯობა.
არ ვიცი როგორ სჯობს ანგულარის აპლიკაციისთვის ვებ სერვერის შექმნა. რომ ვგუგლავ, ყველგან სხვადასხვანაირად წერია. შეგიძლიათ დამაკვალიანოთ?

**Comment by davidgabrichidze** [comment]
მარიამ, ამას გადახედე: https://jsonplaceholder.typicode.com/

არსებობს როგორც გამზადებული fake სერვერი, მზა მეთოდებით, ასევე  საკუთარი  fake სერვერის კონფიგურაციის შესაძლებლობაც.

**Comment by davidgabrichidze** [comment]
ესეც შეგიძლია გამოიყენო: https://jsonbin.io/

**Comment by mariamtsartsidze** [comment]
გმადლობ, გადავხედავ.

**Comment by mariamtsartsidze** [comment]
და აქ როგორც არის, ისე გაკეთება შემიძლია? [https://angular.io/tutorial/toh-pt6](url)

**Comment by davidgabrichidze** [comment]
კი, ეგრეც შეგიძლია.

back-end-ი არ არის პრიორიტეტული ამ ეტაპზე

**Comment by davidgabrichidze** [comment]
მთავარია რომ front-end-დან back-end-ში ინფორმაციის მიმოცვლა გამოჩნდეს

**Comment by mariamtsartsidze** [comment]
გასაგებია, გმადლობ.
