### ISSUE TITLE
Reactive Forms

### ISSUE THREAD

**Issue by davidgabrichidze** [mariamtsartsidze/3Line_webApp#5]
რედაქტირების/ახლის დამატების გვერდი ngModel-იდან გადააწყვე [Reactive Forms](https://angular.io/guide/reactive-forms)-ზე.

გაცილებით უფრო მოსახერხებელი, მართვადი და მარტივი გამოდის კოდი.

ngModel-ის გამოყენება პრიმიტიულ, ერთ/ორ ელემენტიან ფორმებზეა მოსახერხებელი.

**Comment by davidgabrichidze** [comment]
რედაქტირების და დამატების ფორმები ფიზიკურად რომ გააერთიანო უკეთესია.

**Comment by mariamtsartsidze** [comment]
რაც შეეხება რედაქტირებას, გუშინ ძალიან დიდხანს ვეწვალე, მაგრამ ვერ გავასწორე, დავაქომითებ ახლა, როგორიცაა ისეთს. მიწერს, რომ undefined არის ობიექტი და ვერ ვხვდები, რატომ.

**Comment by davidgabrichidze** [comment]
undefinde-ზე აქ გიპასუხე #6

**Comment by davidgabrichidze** [comment]
_ინფორმაციისთვის_: წარმადობისთვის უკეთესია, რომ ფეიჯინგი, სორტირება და ერთი  აითემის წამოღება სერვერის მხარეს მოხდეს ხოლმე. ამ სადემონსტრაციო აპლიკაციაში იყოს ასე. no  prob.  მაგრამ რეალურ  აპლიკაციებში სიის სერვერიდან წამოღება და შემდეგ ლოკალურად გაფილტვრა ფაქტიურად არ  ხდება. სიაც სერვერიდან უკვე სორტირებული მოდის, თან მხოლოდ  იმდენი ჩანაწერი რა ზომაც აქვს ფეიჯინგში მითითებული.

**Comment by mariamtsartsidze** [comment]
დავით, ერთი და იგივე html ფაილი რომ ჰქონდეს რედაქტირებას და დამატებას, მაგრამ ts ცალ-ცალკე, ივარგებს?

**Comment by mariamtsartsidze** [comment]
ისინიც რომ გავაერთიანო, მგონია, რომ აზრობრივად ძალიან აირევა და არ იქნება კარგი.
