### ISSUE TITLE
undefined რედაქტირების ფორმაში

### ISSUE THREAD

**Issue by davidgabrichidze** [mariamtsartsidze/3Line_webApp#6]
html-ში `[(ngModel)]`-ს ენიჭება ობიექტის თვისება (მაგ. `contact.firstName`). ეს ობიექტი კი  html-ის გადახატვისას null-ია.

შეგიძლია, რომ `contact` ცვლადს  თავიდანვე მიანიჭო ინსტანსი:
``` typescript
...
export class EditContactComponent implements OnInit {

  contact: Contact = <Contact>{};
  foodSpecies: string[];

...
```

ან html-ში, ფორმის ველები ჩასვა  div-ში `*ngIf="contact"` დირექტივით.

**Comment by davidgabrichidze** [comment]
მაინც ყველაზე კარგი ვარიანტია ფორმებზე გადააწყო. Reactive Forms-ი უფრო  გამოგადგება.

**Comment by mariamtsartsidze** [comment]
მოგვარდა, კარგი, მასე ვიზამ.
